import fileinput
import re
import sys
if len(sys.argv) > 1:
    iteration = int ((sys.argv[1]))
else:
    iteration = input("Enter iteration:")
print("adding number of instruction",iteration)
count = 0
file_in = "riscv_dv_extension/riscv_core_setting.sv"
if (iteration==0):
    iteration = 160
with fileinput.FileInput(file_in,inplace = True) as f:
    for line in f:
        if (re.search(r"\bLB\b",line) and count<=iteration):
            print(line.replace("LB,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bLH\b",line) and count<=iteration):
            print(line.replace("LH,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bADDI\b",line) and count<=iteration):
            print(line.replace("ADDI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSW\b",line) and count<=iteration):
            print(line.replace("SW,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSH\b",line) and count<=iteration):
            print(line.replace("SH,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSB\b",line) and count<=iteration):
            print(line.replace("SB,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bBGEU\b",line) and count<=iteration):
            print(line.replace("BGEU,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bBLTU\b",line) and count<=iteration):
            print(line.replace("BLTU,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bBGE\b",line) and count<=iteration):
            print(line.replace("BGE,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bBLT\b",line) and count<=iteration):
            print(line.replace("BLT,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bBNE\b",line) and count<=iteration):
            print(line.replace("BNE,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bBEQ\b",line) and count<=iteration):
            print(line.replace("BEQ,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bLW\b",line) and count<=iteration):
            print(line.replace("LW,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bJALR\b",line) and count<=iteration):
            print(line.replace("JALR,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bJAL\b",line) and count<=iteration):
            print(line.replace("JAL,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bLBU\b",line) and count<=iteration): 
            print(line.replace("LBU,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bLHU\b",line) and count<=iteration):
            print(line.replace("LHU,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bLUI\b",line) and count<=iteration):
            print(line.replace("LUI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bAUIPC\b",line) and count<=iteration):
            print(line.replace("AUIPC,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSLTI\b",line) and count<=iteration):
            print(line.replace("SLTI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSLTIU\b",line) and count<=iteration):
            print(line.replace("SLTIU,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bXORI\b",line) and count<=iteration):
            print(line.replace("XORI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bORI\b",line) and count<=iteration):
            print(line.replace("ORI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bANDI\b",line) and count<=iteration):
            print(line.replace("ANDI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSLLI\b",line) and count<=iteration):
            print(line.replace("SLLI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSRLI\b",line) and count<=iteration):
            print(line.replace("SRLI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSRAI\b",line) and count<=iteration):
            print(line.replace("SRAI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bADD\b",line) and count<=iteration):
            print(line.replace("ADD,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSUB\b",line) and count<=iteration):
            print(line.replace("SUB,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSLL\b",line) and count<=iteration):
            print(line.replace("SLL,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSLT\b",line) and count<=iteration):
            print(line.replace("SLT,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSLTU\b",line) and count<=iteration):
            print(line.replace("SLTU,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bXOR\b",line) and count<=iteration):
            print(line.replace("XOR,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSRL\b",line) and count<=iteration):
            print(line.replace("SRL,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bSRA\b",line) and count<=iteration):
            print(line.replace("SRA,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bOR\b",line) and count<=iteration):
            print(line.replace("OR,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bAND\b",line) and count<=iteration):
            print(line.replace("AND,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bNOP\b",line) and count<=iteration):
            print(line.replace("NOP,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bFENCE\b",line) and count<=iteration):
            print(line.replace("FENCE,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bFENCE_I\b",line) and count<=iteration):
            print(line.replace("FENCE_I,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bECALL\b",line) and count<=iteration):
            print(line.replace("ECALL,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bEBREAK\b",line) and count<=iteration):
            print(line.replace("EBREAK,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bCSRRW\b",line) and count<=iteration):
            print(line.replace("CSRRW,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bCSRRS\b",line) and count<=iteration):
            print(line.replace("CSRRS,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bCSRRC\b",line) and count<=iteration):
            print(line.replace("CSRRC,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bCSRRWI\b",line) and count<=iteration):
            print(line.replace("CSRRWI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bCSRRSI\b",line) and count<=iteration):
            print(line.replace("CSRRSI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bCSRRCI\b",line) and count<=iteration):
            print(line.replace("CSRRCI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bMUL\b",line) and count<=iteration):
            print(line.replace("MUL,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bMULH\b",line) and count<=iteration):
            print(line.replace("MULH,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bMULHSU\b",line) and count<=iteration):
            print(line.replace("MULHSU,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bMULHU\b",line) and count<=iteration):
            print(line.replace("MULHU,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bDIV\b",line) and count<=iteration):
            print(line.replace("DIV,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bDIVU\b",line) and count<=iteration):
            print(line.replace("DIVU,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bREM\b",line) and count<=iteration):
            print(line.replace("REM,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bREMU\b",line) and count<=iteration):
            print(line.replace("REMU,", "AMOSWAP_D,",1), end ='')
            count += 1
# From here are the compressed instruction
        elif (re.search(r"\bC_LW\b",line) and count<=iteration):
            print(line.replace("C_LW,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_SW\b",line) and count<=iteration):
            print(line.replace("C_SW,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_LWSP\b",line) and count<=iteration):
            print(line.replace("C_LWSP,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_ADDI4SPN\b",line) and count<=iteration):
            print(line.replace("C_ADDI4SPN,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_ADDI\b",line) and count<=iteration):
            print(line.replace("C_ADDI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_LI\b",line) and count<=iteration):
            print(line.replace("C_LI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_ADDI16SP\b",line) and count<=iteration):
            print(line.replace("C_ADDI16SP,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_LUI\b",line) and count<=iteration):
            print(line.replace("C_LUI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_SRLI\b",line) and count<=iteration):
            print(line.replace("C_SRLI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_SRAI\b",line) and count<=iteration):
            print(line.replace("C_SRAI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_ANDI\b",line) and count<=iteration):
            print(line.replace("C_ANDI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_SUB\b",line) and count<=iteration):
            print(line.replace("C_SUB,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_XOR\b",line) and count<=iteration):
            print(line.replace("C_XOR,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_OR\b",line) and count<=iteration):
            print(line.replace("C_OR,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_AND\b",line) and count<=iteration):
            print(line.replace("C_AND,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_SLLI\b",line) and count<=iteration):
            print(line.replace("C_SLLI,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_MV\b",line) and count<=iteration):
            print(line.replace("C_MV,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_EBREAK\b",line) and count<=iteration):
            print(line.replace("C_EBREAK,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_ADD\b",line) and count<=iteration):
            print(line.replace("C_ADD,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_NOP\b",line) and count<=iteration):
            print(line.replace("C_NOP,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_SWSP\b",line) and count<=iteration):
            print(line.replace("C_SWSP,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_BEQZ\b",line) and count<=iteration):
            print(line.replace("C_BEQZ,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_BNEZ\b",line) and count<=iteration):
            print(line.replace("C_BNEZ,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_J\b",line) and count<=iteration):
            print(line.replace("C_J,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_JAL\b",line) and count<=iteration):
            print(line.replace("C_JAL,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_JALR\b",line) and count<=iteration):
            print(line.replace("C_JALR,", "AMOSWAP_D,",1), end ='')
            count += 1
        elif (re.search(r"\bC_JR\b",line) and count<=iteration):
            print(line.replace("C_JR", "AMOSWAP_D",1), end ='')
            count += 1
        else:
                print(line, end ='')
